apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  DB_USER: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
type: Opaque
data:
  DB_PASSWORD: "YXNob2sxMjM="   # base64 of "ashok123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # deployment labels are used to identify the deployment and its associated resources
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica sets use to create pods. The replica set will create pods with these labels, and the deployment will manage those pods.
  # This should match pod labels in the template section below, so that the deployment can manage the pods it creates.
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  # This is the pod template that defines the pods that will be created by the deployment. The deployment will create pods with these labels, and the replica set will manage those pods.
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      imagePullSecrets:
      - name: ecr-creds
      # This is the container that will be created in the pod. The deployment will create pods  
      containers:
      - name: shipping
        image: 641361263136.dkr.ecr.us-east-1.amazonaws.com/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping
        - secretRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # Service port, this is the port that other pods will use to access the service
    targetPort: 8080 # container port, this is the port that the container is listening on