apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  type: ExternalName
  externalName: mysql.cc78yg45wo1m.us-east-1.rds.amazonaws.com
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306