apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/users"
  REDIS_URL: "redis://redis:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # deployment labels are used to identify the deployment and its associated resources
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  replicas: 1
  # These are the labels replica sets use to create pods. The replica set will create pods with these labels, and the deployment will manage those pods.
  # This should match pod labels in the template section below, so that the deployment can manage the pods it creates.
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  # This is the pod template that defines the pods that will be created by the deployment. The deployment will create pods with these labels, and the replica set will manage those pods.
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: joindevops/user:v1
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # Service port, this is the port that other pods will use to access the service
    targetPort: 8080 # container port, this is the port that the container is listening on